### ISSUE TITLE
name suggestion

### ISSUE THREAD

**Issue by hrdwrrsk** [hrdwrrsk/tetra-gtk-theme#1]
actually, **beaucoup** name are just a placeholder since i'm struggled to find a name, do you have a suggestion for this theme name? just comment here!

update: https://github.com/hrdwrrsk/beaucoup-gtk-theme/issues/1#issuecomment-410177279

**Comment by Triloblob** [comment]
I'm actually okay with the name but gtk2 needs some work. overall I really like this theme
![gtk2_example](https://user-images.githubusercontent.com/41277098/42741900-3cdb1ebe-8884-11e8-942a-dae3896d9927.png)

**Comment by Triloblob** [comment]
oh never mind. reinstalling fixed the issue! 
![nvm](https://user-images.githubusercontent.com/41277098/42742203-1a1c714a-8887-11e8-873f-bd41a94d1c30.png)
