### ISSUE TITLE
New sidebar look

### ISSUE THREAD

**Issue by hrdwrrsk** [hrdwrrsk/tetra-gtk-theme#11]
current WIP:

![screenshot from 2018-11-18 05-49-56](https://user-images.githubusercontent.com/9630564/48666520-277a9700-eaf6-11e8-860e-297c24d92282.png)
![screenshot from 2018-11-18 05-50-23](https://user-images.githubusercontent.com/9630564/48666521-2a758780-eaf6-11e8-8c27-19db79ca4065.png)

note:
- it's looking ugly in gnome-tweaks and gnome-control-center (3.26+) sidebar because of border edge color:

![screenshot from 2018-11-18 05-54-42](https://user-images.githubusercontent.com/9630564/48666527-76c0c780-eaf6-11e8-8c39-56404ede1e61.png)

**Comment by hrdwrrsk** [comment]
reopen for feedback/comments

**Comment by geek1011** [comment]
Thanks! The new sidebar looks nice with Thunar. One possible improvement could be to use a lighter version of the background (instead of white) when the window is unfocused.

**Comment by douglascomim** [comment]
Great job!
It's my favorite theme!
This last update left some backgrounds with the bluish tint ... is this going to be like this or is it a bug?

![2018-11-21_21-43-42](https://user-images.githubusercontent.com/29402875/48873847-4a979600-edd7-11e8-81c3-1b291fcc1769.png)

**Comment by hrdwrrsk** [comment]
> Great job!
> It's my favorite theme!
> This last update left some backgrounds with the bluish tint ... is this going to be like this or is it a bug?
> 
> ![2018-11-21_21-43-42](https://user-images.githubusercontent.com/29402875/48873847-4a979600-edd7-11e8-81c3-1b291fcc1769.png)

Ubuntu 18.10? sorry, it's NOT supported et al. Ubuntu 18.10 doesn't ship with Nautilus (Files) 3.30 (unless if you install flatpak version since gnome3-team ppa is discontinued, or switch to distro with 'complete' GNOME 3.30 like Fedora 29, Debian testing or Arch Linux)

This gtk+ theme contains styling for Nautilus 3.30+ (for gtk+ 3.24), which is not compatible with Nautilus 3.28 (shipped in Ubuntu 18.10, maybe 19.04)

**Comment by theBusterben** [comment]
i like it with the white, but with the dark theme not so much im afraid. the overal feel i get is pretty muted and subtle which i like, but the lighter blueish color throws it off for me. with the white its not that noticable. so what im trying to say is it sticks out too much. maybe a bit lighter of the dark bg would work

**Comment by hrdwrrsk** [comment]
what about dark-ish (and gray-ish in light variant) sidebar look? 

![screenshot from 2018-11-22 17-13-56](https://user-images.githubusercontent.com/9630564/48896361-090bf700-ee7a-11e8-9ce2-e69397a14f88.png)
![screenshot from 2018-11-22 17-14-53](https://user-images.githubusercontent.com/9630564/48896420-293bb600-ee7a-11e8-9cbb-35254fe977bd.png)

**Comment by theBusterben** [comment]
thumbs up for me, looks much better imo

**Comment by hrdwrrsk** [comment]
updated sidebar color it's out in latest commit
