### ISSUE TITLE
close, minimize, maximize buttons missing

### ISSUE THREAD

**Issue by theBusterben** [hrdwrrsk/tetra-gtk-theme#15]
looking at the screenshots seems elementary x + - icons are used. But only xfce4 works with it i guess
Are there plans to add these to gnome theme as well or is that oos?

for gnome folks it falls back to the adwaita theme as its missing headerbar button.titlebutton.close/minimize/maximize (with :backdrop :hover :active etc) in the css

**Comment by hrdwrrsk** [comment]
screenshot?

**Comment by theBusterben** [comment]
ahh yes. thanks for clarifying and thanks for linking the icon theme. its working wonderfully now
