### ISSUE TITLE
Suggestion: Compact variante

### ISSUE THREAD

**Issue by douglascomim** [hrdwrrsk/tetra-gtk-theme#18]
@hrdwrrsk do you think it would be interesting to have a more compact version of the theme?
Which has combox, buttons, inputs ... more narrower.

Well I have a low resolution notebook and a variant like that would be perfect!

Thanks.

**Comment by hrdwrrsk** [comment]
I already attempted for compact version but never worked

The reason is a combobox button/entry are still sized, while other widgets are compact :\

**Comment by douglascomim** [comment]
> I already attempted for compact version but never worked
> 
> The reason is a combobox button/entry are still sized, while other widgets are compact :\

Great!
If I can help o/

**Comment by hrdwrrsk** [comment]
![screenshot from 2019-02-03 10-30-10](https://user-images.githubusercontent.com/9630564/52172302-3b51a300-279f-11e9-91ca-c4398c8068a7.png)
