### ISSUE TITLE
Dark fonts in vala-panel-appmenu and Budgie Calendar Applet (Solus)

### ISSUE THREAD

**Issue by goghard** [hrdwrrsk/tetra-gtk-theme#19]
Hi! Your theme is amazing. I’m using it in Solus Budgie and it looks gorgeous. 
However, I installed vala-panel-appmenu (a global menu add-on) and I noticed that the fonts of the global menu are dark and thin when I’m using your theme:

![image](https://user-images.githubusercontent.com/5067371/49612925-22ca3580-f974-11e8-81cb-35db01949e05.png)

Compare with how it looks with the default theme (Adapta):

![image](https://user-images.githubusercontent.com/5067371/49613002-5f962c80-f974-11e8-9ea4-c523f75b07a1.png)

Is it possible for you to set the fonts for the global menu more bright and bold?

Thanks!

Goghard

P.S. The problem also affects Budgie Calendar Applet

**Comment by danielpinto8zz6** [comment]
about my applet, I fixed, plus I'll add a new pr with a few improvements on calendar soon

**Comment by danielpinto8zz6** [comment]
https://github.com/danielpinto8zz6/budgie-calendar-applet/commit/6c32135f3bf20a6d08d2a5ee967e1552ff0c6699

**Comment by hrdwrrsk** [comment]
ok, it seems 'hacking' budgie-desktop is too hard for me, I need to add :backdrop class for every label widget or they use backdrop text/fg color :\

**Comment by goghard** [comment]
I’m sorry to hear that it is too difficult to fix, but thanks for trying. Is there any workaround I can try?

**Comment by goghard** [comment]
Hi again! 

Turns out that I found a workaround. You can activate the option “Built-in theme” at Budgie Desktop settings, and then the fonts are displayed in a lighter color (not bold, tough.)

**Comment by danielpinto8zz6** [comment]
Built in theme is different from Tetra, it uses arc

**Comment by hrdwrrsk** [comment]
A long time...... it's fixed now as of today
