### ISSUE TITLE
Menubar theming in Qt applications

### ISSUE THREAD

**Issue by apsql** [hrdwrrsk/tetra-gtk-theme#22]
Qt applications' menubar is not correctly themed.

This holds for `sqlitebrowser` and `vlc` as found in the Ubuntu Bionic repositories.
Libreoffice (as pulled in by the `libreoffice` package) is themed just fine.

Gtk applications are themed correctly (e.g., Gnome terminal with Light theme variant).

I use `qt5ct`, setting the environment variable `QT_QPA_PLATFORMTHEME=qt5ct` in `/etc/environment` and by selecting `gtk2` in Qt5ct (screenshot below).

**OS:** Ubuntu 18.04.1 LTS ([minimal installation](https://askubuntu.com/questions/1032718/minimal-installation-details/1036557#1036557))
**GTK theme:** Tetra
**Shell theme:** Tetra Dark

![screenshot from 2019-01-08 16-19-30](https://user-images.githubusercontent.com/24243677/50839844-85429700-1361-11e9-9266-5c38c8c13644.png)

![screenshot from 2019-01-08 15-39-35](https://user-images.githubusercontent.com/24243677/50837958-35fa6780-135d-11e9-99df-50e0290a2e07.png)

![screenshot from 2019-01-08 15-36-45](https://user-images.githubusercontent.com/24243677/50837970-3d217580-135d-11e9-85f1-7985f1b7474a.png)

![screenshot from 2019-01-08 15-37-03](https://user-images.githubusercontent.com/24243677/50837978-401c6600-135d-11e9-975a-bdc93f8bf13b.png)

**Comment by hrdwrrsk** [comment]
it's more like another application/config trying to override qt5 config et al

**Comment by apsql** [comment]
I checked: the problem persists when `QT_QPA_PLATFORMTHEME=gtk2`. So it is not related to `qt5ct`.
