### ISSUE TITLE
Assets rendered as red squares.

### ISSUE THREAD

**Issue by VentGrey** [hrdwrrsk/tetra-gtk-theme#3]
As the title says, assets in this theme are not being rendered correctly, mostly as red squares.

It is strange since I meet the requirements to build it from git.

I use Debian 9.5 with MATE 1.20.x (which uses GTK 3.22), and I also possess the required dependencies mentioned in the **building**  part of the main readme.md file.

Here I attach pics for further details:
![seleccion_005](https://user-images.githubusercontent.com/24773698/46221892-55243a80-c314-11e8-92a7-43a51d50ce5b.png)
![menu_006](https://user-images.githubusercontent.com/24773698/46221900-5a818500-c314-11e8-966f-5f9721cd6ce4.png)

**Comment by hrdwrrsk** [comment]
it seems like assets files got locked permission, try to install it in `~/.themes` or `~/.local/share/themes` folder (without sudo or superuser) !

**Comment by VentGrey** [comment]
It would be useful to see the permissions placed in your `usr/share/themes`, it is weird to see such permission issue since I checked the install.sh script and it doesn't mess with permissions at all. :confused:

**Comment by hrdwrrsk** [comment]
In my investigations, this is caused by ALL files are owned by `dnsmasq` group instead of `users`, but I'm sure this is maybe unrelated with this issue

**Comment by VentGrey** [comment]
Trying to breakpoint the script suggests that the problem with the permissions is in the cp commands under the .sh installation. Apparently in other distros (Tried it on Mageia & Osuse) this issue happens as well, since the cp command transfers the theme with root ownership, maybe I could try to chown / chmod the themes after the whole script installs the theme just for global usability (?)
