### ISSUE TITLE
Theme does work on MATE

### ISSUE THREAD

**Issue by ghost** [hrdwrrsk/tetra-gtk-theme#65]
Even though the README file says otherwise this theme works perfectly under MATE. Have you considered adding it back?

**Comment by rbreaves** [comment]
It doesn't work under my Ubuntu Mate 20.04. The window borders are missing.

**Comment by rbreaves** [comment]
Sorta figured out that it seems like just adding in a metacity xml file for an earlier version, 1, appears to fix it. It’s largely ignored & uses the proper one, 3, so relatively low effort to apparently fix.
